### ISSUE TITLE
Doesn't work in Macbook 

### ISSUE THREAD

**Issue by InstanceDeveloper** [MarkCLewis/Play-Videos#1]
Hi Mark, Tried to follow your video tutorials using this repository as mentioned in the youtube but when executed sbt compile and sbt compile eclipse I'm getting this below errors

Scala code runner version 2.13.2 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.

sbt version in this project: 1.3.10
sbt script version: 1.3.10

personalprojects@s-mbp Play-Videos % sbt compile
[info] Loading settings for project play-videos-build from plugins.sbt,metals.sbt ...
[info] Loading project definition from /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/project
[info] Loading settings for project play-videos from build.sbt ...
[info] Set current project to play-videos (in build file:/Users/personalprojects/Projects/scalaPlayMark/Play-Videos/)
[info] Set current project to Play-Videos-Server (in build file:/Users/personalprojects/Projects/scalaPlayMark/Play-Videos/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 1 Scala source to /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/shared/.js/target/scala-2.12/classes ...
[info] Compiling 6 Scala sources to /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/target/scala-2.12/classes ...
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/LoginComponent.scala:10:8: not found: object models
[error] import models.ReadsAndWrites._
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/LoginComponent.scala:9:8: not found: object models
[error] import models.UserData
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/LoginComponent.scala:55:51: not found: value UserData
[error]     FetchJson.fetchPost(validateRoute, csrfToken, UserData(state.loginName, state.loginPass), (bool: Boolean) => {
[error]                                                   ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/LoginComponent.scala:67:49: not found: value UserData
[error]     FetchJson.fetchPost(createRoute, csrfToken, UserData(state.createName, state.createPass), (bool: Boolean) => {
[error]                                                 ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/Version6.scala:12:8: not found: object models
[error] import models.ReadsAndWrites._
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/TaskListComponent.scala:6:8: not found: object models
[error] import models.ReadsAndWrites._
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/TaskListComponent.scala:5:8: not found: object models
[error] import models.TaskItem
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/TaskListComponent.scala:14:31: not found: type TaskItem
[error]   case class State(tasks: Seq[TaskItem], newTask: String, taskMessage: String)
[error]                               ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/TaskListComponent.scala:45:48: not found: type TaskItem
[error]     FetchJson.fetchGet(tasksRoute, (tasks: Seq[TaskItem]) => {
[error]                                                ^

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "task-progress-report-thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "classloader-cache-cleanup-0"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "sbt-web-scheduler-1"
[error] ## Exception when compiling 6 sources to /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/target/scala-2.12/classes
[error] java.lang.OutOfMemoryError: Java heap space
[error] 
[error]            
java.lang.OutOfMemoryError: Java heap space
[error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Java heap space
personalprojects@s-mbp Play-Videos % scala compile eclipse
No such file or class on classpath: compile
personalprojects@s-mbp Play-Videos % sbt compile eclipse  
[info] Loading settings for project play-videos-build from plugins.sbt,metals.sbt ...
[info] Loading project definition from /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/project
[info] Loading settings for project play-videos from build.sbt ...
[info] Set current project to play-videos (in build file:/Users/personalprojects/Projects/scalaPlayMark/Play-Videos/)
[info] Set current project to Play-Videos-Server (in build file:/Users/personalprojects/Projects/scalaPlayMark/Play-Videos/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 1 Scala source to /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/shared/.js/target/scala-2.12/classes ...
[info] Compiling 6 Scala sources to /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/target/scala-2.12/classes ...
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/LoginComponent.scala:10:8: not found: object models
[error] import models.ReadsAndWrites._
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/LoginComponent.scala:9:8: not found: object models
[error] import models.UserData
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/LoginComponent.scala:55:51: not found: value UserData
[error]     FetchJson.fetchPost(validateRoute, csrfToken, UserData(state.loginName, state.loginPass), (bool: Boolean) => {
[error]                                                   ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/LoginComponent.scala:67:49: not found: value UserData
[error]     FetchJson.fetchPost(createRoute, csrfToken, UserData(state.createName, state.createPass), (bool: Boolean) => {
[error]                                                 ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/Version6.scala:12:8: not found: object models
[error] import models.ReadsAndWrites._
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/TaskListComponent.scala:6:8: not found: object models
[error] import models.ReadsAndWrites._
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/TaskListComponent.scala:5:8: not found: object models
[error] import models.TaskItem
[error]        ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/TaskListComponent.scala:14:31: not found: type TaskItem
[error]   case class State(tasks: Seq[TaskItem], newTask: String, taskMessage: String)
[error]                               ^
[error] /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/src/main/scala/playscala/TaskListComponent.scala:45:48: not found: type TaskItem
[error]     FetchJson.fetchGet(tasksRoute, (tasks: Seq[TaskItem]) => {
[error]                                                ^

[warn] Canceling execution...
Exception in thread "classloader-cache-cleanup-0" java.lang.OutOfMemoryError: Java heap space
	at sbt.internal.classpath.ClassLoaderCache$$Lambda$611/0x0000000801122040.get$Lambda(Unknown Source)
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
	at java.base/java.lang.invoke.Invokers$Holder.linkToTargetMethod(Invokers$Holder)
	at sbt.internal.classpath.ClassLoaderCache.sbt$internal$classpath$ClassLoaderCache$$clearExpiredLoaders(ClassLoaderCache.scala:75)
  | => cat sbt.internal.classpath.ClassLoaderCache$CleanupThread.run(ClassLoaderCache.scala:108)
[error] ## Exception when compiling 6 sources to /Users/personalprojects/Projects/scalaPlayMark/Play-Videos/client/target/scala-2.12/classes
[error] java.lang.OutOfMemoryError: Java heap space
[error] scala.reflect.internal.Symbols$Symbol.info_$eq(Symbols.scala:1562)
[error] scala.reflect.internal.Symbols$Symbol.setInfo(Symbols.scala:1568)
[error] scala.reflect.internal.Symbols$Symbol.modifyInfo(Symbols.scala:1570)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$4(TypeMaps.scala:266)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:266)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$1(TypeMaps.scala:137)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
[error] scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:793)
[error] scala.reflect.internal.Types$Type.subst(Types.scala:747)
[error] scala.reflect.internal.Types$Type.instantiateTypeParams(Types.scala:494)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$matchesPtInst(Implicits.scala:597)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1106)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1138)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1195)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1591)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:111)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
[error] scala.tools.nsc.Global$$anon$4.inferImplicit(Global.scala:482)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
[error] scala.tools.nsc.Global$$anon$4.inferImplicitFor(Global.scala:482)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$applyImplicitArgs$2(Typers.scala:262)
[error] scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:255)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:902)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:490)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1220)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1217)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:772)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:709)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:534)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1107)
[error]            
java.lang.OutOfMemoryError: Java heap space
	at scala.reflect.internal.Symbols$Symbol.info_$eq(Symbols.scala:1562)
	at scala.reflect.internal.Symbols$Symbol.setInfo(Symbols.scala:1568)
	at scala.reflect.internal.Symbols$Symbol.modifyInfo(Symbols.scala:1570)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$4(TypeMaps.scala:266)
  | => cat scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:266)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$1(TypeMaps.scala:137)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:216)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:793)
	at scala.reflect.internal.Types$Type.subst(Types.scala:747)
	at scala.reflect.internal.Types$Type.instantiateTypeParams(Types.scala:494)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$matchesPtInst(Implicits.scala:597)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1106)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1138)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1195)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1591)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:111)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
	at scala.tools.nsc.Global$$anon$4.inferImplicit(Global.scala:482)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
	at scala.tools.nsc.Global$$anon$4.inferImplicitFor(Global.scala:482)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$applyImplicitArgs$2(Typers.scala:262)
	at scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:255)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:902)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:490)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1220)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1217)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:772)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:709)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:534)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1107)
[error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Java heap space

**Comment by MarkCLewis** [comment]
I noticed that one of the first things you pasted lists Scala 2.13. I did everything with Scala 2.12. It does appear that you are compiling with 2.12 though, so I'm not certain if that is the issue. The running out of memory is worrisome, but that seems to happen after the compile errors. I'm a firm believer in starting with the first error. In this case, it says that there is no models. In my code, models.ReadsAndWritesscala is in the shared subproject. So my first suggestion would be to go look and make sure you have that.

**Comment by porl** [comment]
I get the same error. From the repository it seems that the shared directory only contains a test stub. Is there perhaps an issue with git not syncing everything to here?

**Comment by porl** [comment]
Looking more closely, I noticed a /scala/ entry in a .gitignore file in the shared/src/main/ directory from the "After adding in a view" commit which would stop any future changes you made there from propagating.

**Comment by MarkCLewis** [comment]
I just removed the .gitignore and redid the commit and push. I honestly have no idea how that .gitignore file got that.

**Comment by porl** [comment]
Much better thanks!
