### ISSUE TITLE
Potential vulnerability for deletions?

### ISSUE THREAD

**Issue by MackHartley** [MarkCLewis/Play-Videos#2]
Hi Mark, great tutorials. I have been following your tutorials loosely while building a Scala Play rest API for an Android app using token based auth. One thing I realized is that this line was a security risk for my use case:
https://github.com/MarkCLewis/Play-Videos/blob/master/server/app/models/TaskListDatabaseModel.scala#L47

```
def removeTask(itemId: Int): Future[Boolean] = {
    db.run( Items.filter(_.itemId === itemId).delete ).map(count => count > 0)
  }
```

Any call (that passes authentication) was able to provide any todo ID to delete, regardless if that ID belonged to the user sending the call. I was able to fix this issue with the below code:

```
db.run(
      Items
        .filter(_.itemId === targetItemId)
        .filter(_.userId === userId)
        .delete
    ).map(count => count > 0)
```

Like I said above, I'm using token auth instead of sessions, so perhaps this issue isn't present in your code, it's a bit hard for me to tell. I just figured I would bring this to your attention.

**Comment by MarkCLewis** [comment]
You are correct. I didn't bother to check that the item being deleted was owned by the person making the request, but this would fix that.
